skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
week6_profile = "EgvAE7sfipvKGE4wa238K1E5WK2HNFVJ4qcsJ4dn5KRg"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
